/***************************************************
 * WARNING: This file was autogenerated by msgenc. *
 *               DO NOT MODIFY                     *
 ***************************************************/

#ifndef FS_MSGDATA_CONTEST_EFFECTS_H
#define FS_MSGDATA_CONTEST_EFFECTS_H

// Perform first
#define CONTEST_EFFECTS_PerformFirst 0
// next turn.
#define CONTEST_EFFECTS_NextTurn1 1
// Perform last
#define CONTEST_EFFECTS_PerformLast 2
// next turn.
#define CONTEST_EFFECTS_NextTurn2 3
// Each doubled
#define CONTEST_EFFECTS_EachDoubled 4
// Judge: +2
#define CONTEST_EFFECTS_JudgePlusTwo 5
// If the Voltage
#define CONTEST_EFFECTS_IfTheVoltage 6
// goes up: +2
#define CONTEST_EFFECTS_GoesUpPlusTwo 7
// A basic act.
#define CONTEST_EFFECTS_BasicAct 8
//  
#define CONTEST_EFFECTS_Unused 9
// If Judges are
#define CONTEST_EFFECTS_IfJudgesAre 10
// not doubled: +3
#define CONTEST_EFFECTS_NotDoubledPlusThree 11
// Performable two
#define CONTEST_EFFECTS_PerformableTwo 12
// turns in a row.
#define CONTEST_EFFECTS_TurnsInARow 13
// Voltage pts.
#define CONTEST_EFFECTS_VoltagePts 14
// are added.
#define CONTEST_EFFECTS_AreAdded 15
// If all choose
#define CONTEST_EFFECTS_IfAllChoose 16
// same Judge: +15
#define CONTEST_EFFECTS_SameJudgePlusFifteen 17
// Lowers Voltage
#define CONTEST_EFFECTS_LowersVoltage 18
// of Judges by 1.
#define CONTEST_EFFECTS_OfJudgesByOne 19
// Double score in
#define CONTEST_EFFECTS_DoubleScoreIn 20
// next turn.
#define CONTEST_EFFECTS_NextTurn3 21
// Get Voltage
#define CONTEST_EFFECTS_GetVoltage 22
// from one ahead.
#define CONTEST_EFFECTS_FromOneAhead 23
// No Voltage up
#define CONTEST_EFFECTS_NoVoltageUp 24
// this turn.
#define CONTEST_EFFECTS_ThisTurn1 25
// Random order
#define CONTEST_EFFECTS_RandomOrder 26
// next turn.
#define CONTEST_EFFECTS_NextTurn4 27
// Double score
#define CONTEST_EFFECTS_DoubleScore 28
// for final act.
#define CONTEST_EFFECTS_ForFinalAct 29
// High score for
#define CONTEST_EFFECTS_HighScoreFor1 30
// low Voltage.
#define CONTEST_EFFECTS_LowVoltage 31
// If first
#define CONTEST_EFFECTS_IfFirst 32
// performance: +2
#define CONTEST_EFFECTS_PerformancePlusTwo1 33
// If final
#define CONTEST_EFFECTS_IfFinal 34
// performance: +2
#define CONTEST_EFFECTS_PerformancePlusTwo2 35
// No Voltage down
#define CONTEST_EFFECTS_NoVoltageDown 36
// this turn.
#define CONTEST_EFFECTS_ThisTurn2 37
// If Voltage goes
#define CONTEST_EFFECTS_IfVoltageGoes 38
// up in a row: +3
#define CONTEST_EFFECTS_UpInARowPlusThree 39
// High score for
#define CONTEST_EFFECTS_HighScoreFor2 40
// a later turn.
#define CONTEST_EFFECTS_ALaterTurn 41
// After Voltage
#define CONTEST_EFFECTS_AfterVoltage 42
// hits max: +3
#define CONTEST_EFFECTS_HitsMaxPlusThree 43
// If rated the
#define CONTEST_EFFECTS_IfRatedThe 44
// worst: +3
#define CONTEST_EFFECTS_WorstPlusThree 45
// Enables the user to
// perform first in the
// next turn.
#define CONTEST_EFFECTS_00046 46
// Enables the user to
// perform last in the
// next turn.
#define CONTEST_EFFECTS_00047 47
// Earn +2 for each
// time the same Judge
// is chosen.
#define CONTEST_EFFECTS_00048 48
// Earn +2 if the
// Judge’s Voltage goes
// up.
#define CONTEST_EFFECTS_00049 49
// A basic performance
// using a move known
// by the Pokémon.
#define CONTEST_EFFECTS_00050 50
// Earn +3 if no other
// Pokémon has chosen
// the same Judge.
#define CONTEST_EFFECTS_00051 51
// Allows performance
// of the same move
// twice in a row.
#define CONTEST_EFFECTS_00052 52
// Increased Voltage is
// added to the
// performance score.
#define CONTEST_EFFECTS_00053 53
// Earn +15 if all the
// Pokémon choose the
// same Judge.
#define CONTEST_EFFECTS_00054 54
// Lowers the Voltage
// of all Judges by one
// each.
#define CONTEST_EFFECTS_00055 55
// Earn double the
// score in the next
// turn.
#define CONTEST_EFFECTS_00056 56
// Steals the Voltage
// of the Pokémon that
// just went.
#define CONTEST_EFFECTS_00057 57
// Prevents the Voltage
// from going up in the
// same turn.
#define CONTEST_EFFECTS_00058 58
// Makes the order of
// contestants random
// in the next turn.
#define CONTEST_EFFECTS_00059 59
// Earns double the
// score on the final
// performance.
#define CONTEST_EFFECTS_00060 60
// Raises the score if
// the Voltage is low.
#define CONTEST_EFFECTS_00061 61
// Earn +2 if the
// Pokémon performs
// first in the turn.
#define CONTEST_EFFECTS_00062 62
// Earn +2 if the
// Pokémon performs
// last in the turn.
#define CONTEST_EFFECTS_00063 63
// Prevents the Voltage
// from going down in
// the same turn.
#define CONTEST_EFFECTS_00064 64
// Earn +3 if two
// Pokémon raise the
// Voltage in a row.
#define CONTEST_EFFECTS_00065 65
// Earn a higher score
// the later the
// Pokémon performs.
#define CONTEST_EFFECTS_00066 66
// Earn +3 if the
// Pokémon that just
// went hit max Voltage.
#define CONTEST_EFFECTS_00067 67
// Earn +3 if the
// Pokémon gets the
// lowest score.
#define CONTEST_EFFECTS_00068 68

#define TEXT_BANK_CONTEST_EFFECTS_ENTRY_COUNT 69

#endif // FS_MSGDATA_CONTEST_EFFECTS_H
