#ifndef FS_MSGDATA_TEXT_BANK_LOCATION_NAMES_H
#define FS_MSGDATA_TEXT_BANK_LOCATION_NAMES_H

// Mystery Zone
#define LOCATION_NAME_MysteryZone 0
// Twinleaf Town
#define LOCATION_NAME_TwinleafTown 1
// Sandgem Town
#define LOCATION_NAME_SandgemTown 2
// Floaroma Town
#define LOCATION_NAME_FloaromaTown 3
// Solaceon Town
#define LOCATION_NAME_SolaceonTown 4
// Celestic Town
#define LOCATION_NAME_CelesticTown 5
// Jubilife City
#define LOCATION_NAME_JubilifeCity 6
// Canalave City
#define LOCATION_NAME_CanalaveCity 7
// Oreburgh City
#define LOCATION_NAME_OreburghCity 8
// Eterna City
#define LOCATION_NAME_EternaCity 9
// Hearthome City
#define LOCATION_NAME_HearthomeCity 10
// Pastoria City
#define LOCATION_NAME_PastoriaCity 11
// Veilstone City
#define LOCATION_NAME_VeilstoneCity 12
// Sunyshore City
#define LOCATION_NAME_SunyshoreCity 13
// Snowpoint City
#define LOCATION_NAME_SnowpointCity 14
// Pokémon League
#define LOCATION_NAME_PokemonLeague 15
// Route 201
#define LOCATION_NAME_Route201 16
// Route 202
#define LOCATION_NAME_Route202 17
// Route 203
#define LOCATION_NAME_Route203 18
// Route 204
#define LOCATION_NAME_Route204 19
// Route 205
#define LOCATION_NAME_Route205 20
// Route 206
#define LOCATION_NAME_Route206 21
// Route 207
#define LOCATION_NAME_Route207 22
// Route 208
#define LOCATION_NAME_Route208 23
// Route 209
#define LOCATION_NAME_Route209 24
// Route 210
#define LOCATION_NAME_Route210 25
// Route 211
#define LOCATION_NAME_Route211 26
// Route 212
#define LOCATION_NAME_Route212 27
// Route 213
#define LOCATION_NAME_Route213 28
// Route 214
#define LOCATION_NAME_Route214 29
// Route 215
#define LOCATION_NAME_Route215 30
// Route 216
#define LOCATION_NAME_Route216 31
// Route 217
#define LOCATION_NAME_Route217 32
// Route 218
#define LOCATION_NAME_Route218 33
// Route 219
#define LOCATION_NAME_Route219 34
// Route 220
#define LOCATION_NAME_Route220 35
// Route 221
#define LOCATION_NAME_Route221 36
// Route 222
#define LOCATION_NAME_Route222 37
// Route 223
#define LOCATION_NAME_Route223 38
// Route 224
#define LOCATION_NAME_Route224 39
// Route 225
#define LOCATION_NAME_Route225 40
// Route 226
#define LOCATION_NAME_Route226 41
// Route 227
#define LOCATION_NAME_Route227 42
// Route 228
#define LOCATION_NAME_Route228 43
// Route 229
#define LOCATION_NAME_Route229 44
// Route 230
#define LOCATION_NAME_Route230 45
// Oreburgh Mine
#define LOCATION_NAME_OreburghMine 46
// Valley Windworks
#define LOCATION_NAME_ValleyWindworks 47
// Eterna Forest
#define LOCATION_NAME_EternaForest 48
// Fuego Ironworks
#define LOCATION_NAME_FuegoIronworks 49
// Mt. Coronet
#define LOCATION_NAME_MtCoronet 50
// Spear Pillar
#define LOCATION_NAME_SpearPillar 51
// Great Marsh
#define LOCATION_NAME_GreatMarsh 52
// Solaceon Ruins
#define LOCATION_NAME_SolaceonRuins 53
// Victory Road
#define LOCATION_NAME_VictoryRoad 54
// Pal Park
#define LOCATION_NAME_PalPark 55
// Amity Square
#define LOCATION_NAME_AmitySquare 56
// Ravaged Path
#define LOCATION_NAME_RavagedPath 57
// Floaroma Meadow
#define LOCATION_NAME_FloaromaMeadow 58
// Oreburgh Gate
#define LOCATION_NAME_OreburghGate 59
// Fullmoon Island
#define LOCATION_NAME_FullmoonIsland 60
// Sendoff Spring
#define LOCATION_NAME_SendoffSpring 61
// Turnback Cave
#define LOCATION_NAME_TurnbackCave 62
// Flower Paradise
#define LOCATION_NAME_FlowerParadise 63
// Snowpoint Temple
#define LOCATION_NAME_SnowpointTemple 64
// Wayward Cave
#define LOCATION_NAME_WaywardCave 65
// Ruin Maniac Cave
#define LOCATION_NAME_RuinManiacCave 66
// Maniac Tunnel
#define LOCATION_NAME_ManiacTunnel 67
// Trophy Garden
#define LOCATION_NAME_TrophyGarden 68
// Iron Island
#define LOCATION_NAME_IronIsland 69
// Old Chateau
#define LOCATION_NAME_OldChateau 70
// Galactic HQ
#define LOCATION_NAME_GalacticHQ 71
// Verity Lakefront
#define LOCATION_NAME_VerityLakefront 72
// Valor Lakefront
#define LOCATION_NAME_ValorLakefront 73
// Acuity Lakefront
#define LOCATION_NAME_AcuityLakefront 74
// Spring Path
#define LOCATION_NAME_SpringPath 75
// Lake Verity
#define LOCATION_NAME_LakeVerity 76
// Lake Valor
#define LOCATION_NAME_LakeValor 77
// Lake Acuity
#define LOCATION_NAME_LakeAcuity 78
// Newmoon Island
#define LOCATION_NAME_NewmoonIsland 79
// Battle Tower
#define LOCATION_NAME_BattleTower 80
// Fight Area
#define LOCATION_NAME_FightArea 81
// Survival Area
#define LOCATION_NAME_SurvivalArea 82
// Resort Area
#define LOCATION_NAME_ResortArea 83
// Stark Mountain
#define LOCATION_NAME_StarkMountain 84
// Seabreak Path
#define LOCATION_NAME_SeabreakPath 85
// Hall of Origin
#define LOCATION_NAME_HallOfOrigin 86
// Verity Cavern
#define LOCATION_NAME_VerityCavern 87
// Valor Cavern
#define LOCATION_NAME_ValorCavern 88
// Acuity Cavern
#define LOCATION_NAME_AcuityCavern 89
// Jubilife TV
#define LOCATION_NAME_JubilifeTV 90
// Pokétch Co.
#define LOCATION_NAME_PoketchCo 91
// GTS
#define LOCATION_NAME_GTS 92
// Trainers’ School
#define LOCATION_NAME_TrainersSchool 93
// Mining Museum
#define LOCATION_NAME_MiningMuseum 94
// Flower Shop
#define LOCATION_NAME_FlowerShop 95
// Cycle Shop
#define LOCATION_NAME_CycleShop 96
// Contest Hall
#define LOCATION_NAME_ContestHall 97
// Poffin House
#define LOCATION_NAME_PoffinHouse 98
// Foreign Building
#define LOCATION_NAME_ForeignBuilding 99
// Pokémon Day Care
#define LOCATION_NAME_PokemonDayCare 100
// Veilstone Store
#define LOCATION_NAME_VeilstoneStore 101
// Game Corner
#define LOCATION_NAME_GameCorner 102
// Canalave Library
#define LOCATION_NAME_CanalaveLibrary 103
// Vista Lighthouse
#define LOCATION_NAME_VistaLighthouse 104
// Sunyshore Market
#define LOCATION_NAME_SunyshoreMarket 105
// Pokémon Mansion
#define LOCATION_NAME_PokemonMansion 106
// Footstep House
#define LOCATION_NAME_FootstepHouse 107
// Café
#define LOCATION_NAME_Cafe 108
// Grand Lake
#define LOCATION_NAME_GrandLake 109
// Restaurant
#define LOCATION_NAME_Restaurant 110
// Battle Park
#define LOCATION_NAME_BattlePark 111
// Battle Frontier
#define LOCATION_NAME_BattleFrontier 112
// Battle Factory
#define LOCATION_NAME_BattleFactory 113
// Battle Castle
#define LOCATION_NAME_BattleCastle 114
// Battle Arcade
#define LOCATION_NAME_BattleArcade 115
// Battle Hall
#define LOCATION_NAME_BattleHall 116
// Distortion World
#define LOCATION_NAME_DistortionWorld 117
// Global Terminal
#define LOCATION_NAME_GlobalTerminal 118
// Villa
#define LOCATION_NAME_Villa 119
// Battleground
#define LOCATION_NAME_Battleground 120
// ROTOM’s Room
#define LOCATION_NAME_RotomsRoom 121
// T.G. Eterna Bldg
#define LOCATION_NAME_TeamGalacticEternaBuilding 122
// Iron Ruins
#define LOCATION_NAME_IronRuins 123
// Iceberg Ruins
#define LOCATION_NAME_IcebergRuins 124
// Rock Peak Ruins
#define LOCATION_NAME_RockPeakRuins 125
#define TEXT_BANK_LOCATION_NAMES_ENTRY_COUNT 126

#endif // FS_MSGDATA_TEXT_BANK_LOCATION_NAMES_H
