#ifndef MPR_POKEMON_SUMMARY_SCREEN_SUMMARY_SCREEN_3D_ANIM_H
#define MPR_POKEMON_SUMMARY_SCREEN_SUMMARY_SCREEN_3D_ANIM_H

#include "applications/pokemon_summary_screen/summary_screen_main.h"

void PokemonSummaryScreen_Setup3DGfx(PokemonSummaryScreen* summaryScreen);
void PokemonSummaryScreen_Update3DGfx(PokemonSummaryScreen* summaryScreen);
void PokemonSummaryScreen_FreeCameraAndMonSprite(PokemonSummaryScreen* summaryScreen);
void PokemonSummaryScreen_SetupCamera(PokemonSummaryScreen* summaryScreen);
void PokemonSummaryScreen_InitConditionRects(PokemonSummaryScreen* summaryScreen);
void PokemonSummaryScreen_InitMaxAndDeltaConditionRects(PokemonSummaryScreen* summaryScreen);
void PokemonSummaryScreen_LoadMonSprite(PokemonSummaryScreen* summaryScreen);
void PokemonSummaryScreen_LoadMonAnimation(PokemonSummaryScreen* summaryScreen);
void PokemonSummaryScreen_ChangeMonSprite(PokemonSummaryScreen* summaryScreen);

#endif /* MPR_POKEMON_SUMMARY_SCREEN_SUMMARY_SCREEN_3D_ANIM_H */
