#ifndef MPR_CONSTANTS_CONTEST_H
#define MPR_CONSTANTS_CONTEST_H

#define CONTEST_MODE_OFFICIAL  0
#define CONTEST_MODE_LINK      1
#define CONTEST_MODE_PRACTICE  2

#define CONTEST_COMPETITION_UNK0              0
#define CONTEST_COMPETITION_UNK1              1
#define CONTEST_COMPETITION_LINK_OR_OFFICIAL  2
#define CONTEST_COMPETITION_PRACTICE_VISUAL   3
#define CONTEST_COMPETITION_VISUAL            4
#define CONTEST_COMPETITION_PRACTICE_DANCE    5
#define CONTEST_COMPETITION_DANCE             6
#define CONTEST_COMPETITION_PRACTICE_ACTING   7
#define CONTEST_COMPETITION_ACTING            8

#define CONTEST_NUM_PARTICIPANTS  4
#define CONTEST_NUM_JUDGES        3

#define POINTS_PER_APPEAL_HEART  10
#define MAX_APPEAL_HEARTS        6

#define PLAYER_CONTESTANT_ID  0

typedef enum {
	CONTEST_TYPE_COOL,
	CONTEST_TYPE_BEAUTY,
	CONTEST_TYPE_CUTE,
	CONTEST_TYPE_SMART,
	CONTEST_TYPE_TOUGH,
	CONTEST_TYPE_MAX
} ContestType;

#endif /* MPR_CONSTANTS_CONTEST_H */
