#ifndef MPR_CONSTANTS_FLAVOR_H
#define MPR_CONSTANTS_FLAVOR_H

typedef enum {
	FLAVOR_SPICY = 0,
	FLAVOR_DRY,
	FLAVOR_SWEET,
	FLAVOR_BITTER,
	FLAVOR_SOUR,
	FLAVOR_MAX,
	
	FLAVOR_NONE = FLAVOR_MAX
} Flavor;

#endif /* MPR_CONSTANTS_FLAVOR_H */
