#ifndef MPR_CONSTANTS_GENDER_RATIOS_H
#define MPR_CONSTANTS_GENDER_RATIOS_H

typedef enum {
	GENDER_RATIO_MALE_ONLY   =   0,
	GENDER_RATIO_FEMALE_12_5 =  31,
	GENDER_RATIO_FEMALE_25   =  63,
	GENDER_RATIO_FEMALE_50   = 127,
	GENDER_RATIO_FEMALE_75   = 191,
	GENDER_RATIO_FEMALE_87_5 = 223,
	GENDER_RATIO_FEMALE_ONLY = 254,
	GENDER_RATIO_NO_GENDER   = 255
} GenderRatio;

#endif /* MPR_CONSTANTS_GENDER_RATIOS_H */
