#ifndef MPR_CONSTANTS_MOVE_ATTRIBUTES_H
#define MPR_CONSTANTS_MOVE_ATTRIBUTES_H

typedef enum {
	MOVEATTRIBUTE_EFFECT         =  0,
	MOVEATTRIBUTE_CLASS          =  1,
	MOVEATTRIBUTE_POWER          =  2,
	MOVEATTRIBUTE_TYPE           =  3,
	MOVEATTRIBUTE_ACCURACY       =  4,
	MOVEATTRIBUTE_PP             =  5,
	MOVEATTRIBUTE_EFFECT_CHANCE  =  6,
	MOVEATTRIBUTE_RANGE          =  7,
	MOVEATTRIBUTE_PRIORTY        =  8,
	MOVEATTRIBUTE_FLAGS          =  9,
	MOVEATTRIBUTE_CONTEST_EFFECT = 10,
	MOVEATTRIBUTE_CONTEST_TYPE   = 11
} MoveAttribute;

#endif /* MPR_CONSTANTS_MOVE_ATTRIBUTES_H */
