#ifndef MPR_CONSTANTS_MOVE_CLASSES_H
#define MPR_CONSTANTS_MOVE_CLASSES_H

typedef enum {
	CLASS_PHYSICAL = 0,
	CLASS_SPECIAL  = 1,
	CLASS_STATUS   = 2
} MoveClass;

#endif /* MPR_CONSTANTS_MOVE_CLASSES_H */
