#ifndef MPR_CONSTANTS_NATURES_H
#define MPR_CONSTANTS_NATURES_H

typedef enum {
	NATURE_HARDY   =  0,
	NATURE_LONELY  =  1,
	NATURE_BRAVE   =  2,
	NATURE_ADAMANT =  3,
	NATURE_NAUGHTY =  4,
	NATURE_BOLD    =  5,
	NATURE_DOCILE  =  6,
	NATURE_RELAXED =  7,
	NATURE_IMPISH  =  8,
	NATURE_LAX     =  9,
	NATURE_TIMID   = 10,
	NATURE_HASTY   = 11,
	NATURE_SERIOUS = 12,
	NATURE_JOLLY   = 13,
	NATURE_NAIVE   = 14,
	NATURE_MODEST  = 15,
	NATURE_MILD    = 16,
	NATURE_QUIET   = 17,
	NATURE_BASHFUL = 18,
	NATURE_RASH    = 19,
	NATURE_CALM    = 20,
	NATURE_GENTLE  = 21,
	NATURE_SASSY   = 22,
	NATURE_CAREFUL = 23,
	NATURE_QUIRKY  = 24,
	NATURE_MAX     = 25
} Nature;

#endif /* MPR_CONSTANTS_NATURES_H */
