#ifndef MPR_CONSTANTS_POKEMON_CONTEST_TYPES_H
#define MPR_CONSTANTS_POKEMON_CONTEST_TYPES_H

typedef enum {
	CONTEST_TYPE_COOL   = 0,
	CONTEST_TYPE_BEAUTY = 1,
	CONTEST_TYPE_CUTE   = 2,
	CONTEST_TYPE_SMART  = 3,
	CONTEST_TYPE_TOUGH  = 4,
	CONTEST_TYPE_MAX    = 5
} PokemonContestType;

#endif /* MPR_CONSTANTS_POKEMON_CONTEST_TYPES_H */
