#ifndef MPR_CONSTANTS_POKEMON_CONDITIONS
#define MPR_CONSTANTS_POKEMON_CONDITIONS

#define MON_CONDITION_NONE             (0)
#define MON_CONDITION_SLEEP_0          (1 << 0)
#define MON_CONDITION_SLEEP_1          (1 << 1)
#define MON_CONDITION_SLEEP_2          (1 << 2)
#define MON_CONDITION_POISON           (1 << 3)
#define MON_CONDITION_BURN             (1 << 4)
#define MON_CONDITION_FREEZE           (1 << 5)
#define MON_CONDITION_PARALYSIS        (1 << 6)
#define MON_CONDITION_TOXIC            (1 << 7)
#define MON_CONDITION_TOXIC_COUNTER_0  (1 << 8)
#define MON_CONDITION_TOXIC_COUNTER_1  (1 << 9)
#define MON_CONDITION_TOXIC_COUNTER_2  (1 << 10)
#define MON_CONDITION_TOXIC_COUNTER_3  (1 << 11)

#define MON_CONDITION_TOXIC_COUNT_INC  MON_CONDITION_TOXIC_COUNTER_0

#define MON_CONDITION_SLEEP          (MON_CONDITION_SLEEP_0 | MON_CONDITION_SLEEP_1 | MON_CONDITION_SLEEP_2)
#define MON_CONDITION_TOXIC_COUNTER  (MON_CONDITION_TOXIC_COUNTER_0 | MON_CONDITION_TOXIC_COUNTER_1 | MON_CONDITION_TOXIC_COUNTER_2 | MON_CONDITION_TOXIC_COUNTER_3)
#define MON_CONDITION_ANY_POISON     (MON_CONDITION_POISON | MON_CONDITION_TOXIC | MON_CONDITION_TOXIC_COUNTER)
#define MON_CONDITION_ANY            (MON_CONDITION_SLEEP | MON_CONDITION_POISON | MON_CONDITION_BURN | MON_CONDITION_FREEZE | MON_CONDITION_PARALYSIS | MON_CONDITION_TOXIC)

#define MON_CONDITION_NOT_SLEEP        (~MON_CONDITION_SLEEP)
#define MON_CONDITION_CAN_SYNCHRONIZE  (MON_CONDITION_POISON | MON_CONDITION_BURN | MON_CONDITION_PARALYSIS)
#define MON_CONDITION_FACADE_BOOST     (MON_CONDITION_TOXIC | MON_CONDITION_POISON | MON_CONDITION_BURN | MON_CONDITION_PARALYSIS)

#endif /* MPR_CONSTANTS_POKEMON_CONDITIONS */
