#ifndef MPR_CONSTANTS_POKEMON_COLORS_H
#define MPR_CONSTANTS_POKEMON_COLORS_H

typedef enum {
	MON_COLOR_RED    =  0,
	MON_COLOR_BLUE   =  1,
	MON_COLOR_YELLOW =  2,
	MON_COLOR_GREEN  =  3,
	MON_COLOR_BLACK  =  4,
	MON_COLOR_BROWN  =  5,
	MON_COLOR_PURPLE =  6,
	MON_COLOR_GRAY   =  7,
	MON_COLOR_WHITE  =  8,
	MON_COLOR_PINK   =  9,
	MON_COLOR_EGG    = 10,
	NUM_MON_COLORS   = 11
} PokemonColor;

#endif /* MPR_CONSTANTS_POKEMON_COLORS_H */
