#ifndef MPR_CONSTANTS_SOUND_H
#define MPR_CONSTANTS_SOUND_H

typedef enum {
	POKECRY_NORMAL = 0,
	POKECRY_HALF_DURATION,
	POKECRY_FIELD_EVENT,
	POKECRY_MID_MOVE,
	POKECRY_HYPERVOICE_1,
	POKECRY_FAINT,
	POKECRY_HYPERVOICE_2,
	POKECRY_HOWL_1,
	POKECRY_HOWL_2,
	POKECRY_UPROAR_1,
	POKECRY_UPROAR_2,
	POKECRY_PINCH_NORMAL,
	POKECRY_PINCH_HALF_DURATION,
	POKECRY_POKEDEX_CHORUS,
	POKECRY_POKEDEX
} PokemonCryMod;

#endif /* MPR_CONSTANTS_SOUND_H */
