#ifndef MPR_CONSTANTS_SPECIES_DATA_PARAMS_H
#define MPR_CONSTANTS_SPECIES_DATA_PARAMS_H

typedef enum {
	SPECIES_DATA_BASE_HP            =  0,
	SPECIES_DATA_BASE_ATK           =  1,
	SPECIES_DATA_BASE_DEF           =  2,
	SPECIES_DATA_BASE_SPEED         =  3,
	SPECIES_DATA_BASE_SP_ATK        =  4,
	SPECIES_DATA_BASE_SP_DEF        =  5,
	SPECIES_DATA_TYPE_1             =  6,
	SPECIES_DATA_TYPE_2             =  7,
	SPECIES_DATA_CATCH_RATE         =  8,
	SPECIES_DATA_BASE_EXP_REWARD    =  9,
	SPECIES_DATA_EV_HP_YIELD        = 10,
	SPECIES_DATA_EV_ATK_YIELD       = 11,
	SPECIES_DATA_EV_DEF_YIELD       = 12,
	SPECIES_DATA_EV_SPEED_YIELD     = 13,
	SPECIES_DATA_EV_SP_ATK_YIELD    = 14,
	SPECIES_DATA_EV_SP_DEF_YIELD    = 15,
	SPECIES_DATA_HELD_ITEM_COMMON   = 16,
	SPECIES_DATA_HELD_ITEM_RARE     = 17,
	SPECIES_DATA_GENDER_RATIO       = 18,
	SPECIES_DATA_HATCH_CYCLES       = 19,
	SPECIES_DATA_BASE_FRIENDSHIP    = 20,
	SPECIES_DATA_EXP_RATE           = 21,
	SPECIES_DATA_EGG_GROUP_1        = 22,
	SPECIES_DATA_EGG_GROUP_2        = 23,
	SPECIES_DATA_ABILITY_1          = 24,
	SPECIES_DATA_ABILITY_2          = 25,
	SPECIES_DATA_SAFARI_FLEE_RATE   = 26,
	SPECIES_DATA_BODY_COLOR         = 27,
	SPECIES_DATA_FLIP_SPRITE        = 28,
	SPECIES_DATA_TM_LEARNSET_MASK_1 = 29,
	SPECIES_DATA_TM_LEARNSET_MASK_2 = 30,
	SPECIES_DATA_TM_LEARNSET_MASK_3 = 31,
	SPECIES_DATA_TM_LEARNSET_MASK_4 = 32
} SpeciesDataParam;

#endif /* MPR_CONSTANTS_SPECIES_DATA_PARAMS_H */
