#ifndef MPR_EASY_CHAT_SENTENCE_H
#define MPR_EASY_CHAT_SENTENCE_H

#include "constants/heap.h"

#include "string_gf.h"

#define MAX_EASY_CHAT_SENTENCE_WORD_SLOTS      2
#define FRONTIER_EASY_CHAT_SENTENCE_TYPE_NO_1  3

typedef struct {
	u16  type;
	u16  id;
	u16  words[MAX_EASY_CHAT_SENTENCE_WORD_SLOTS];
} EasyChatSentence;

typedef enum {
	EASY_CHAT_SENTENCE_TYPE_NONE = 0xFFFF,
	EASY_CHAT_SENTENCE_TYPE_PRE_BATTLE = 0,
	EASY_CHAT_SENTENCE_TYPE_WIN,
	EASY_CHAT_SENTENCE_TYPE_LOSS,
	EASY_CHAT_SENTENCE_TYPE_GENERAL,
	EASY_CHAT_SENTENCE_TYPE_UNION_ROOM,
	EASY_CHAT_SENTENCE_TYPE_COUNT,
} EasyChatSentenceType;

#endif /* MPR_EASY_CHAT_SENTENCE_H */
