#ifndef MPR_GX_GF_H
#define MPR_GX_GF_H

#define GX_BLEND_BGALL  (GX_BLEND_PLANEMASK_BG0 | GX_BLEND_PLANEMASK_BG1 | GX_BLEND_PLANEMASK_BG2 | GX_BLEND_PLANEMASK_BG3)
#define GX_BLEND_ALL    (GX_BLEND_BGALL | GX_BLEND_PLANEMASK_OBJ | GX_BLEND_PLANEMASK_BD)

void GFGX_Init(void);
void GFGX_ResetG3X(void);
void GFGX_SwapBuffers(void);

#endif /* MPR_GX_GF_H */
